# Importing Libraries and Data collection

In [60]:
import pandas as pd

In [61]:
df_org=pd.read_csv('udemy_course_data.csv')

In [62]:
df_org.head()

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,profit,published_date,published_time,year,month,day
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5 hours,2017-01-18T20:58:58Z,Business Finance,429400,2017-01-18,20:58:58Z,2017,1,18
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39 hours,2017-03-09T16:34:20Z,Business Finance,209400,2017-03-09,16:34:20Z,2017,3,9
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5 hours,2016-12-19T19:26:30Z,Business Finance,97830,2016-12-19,19:26:30Z,2016,12,19
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3 hours,2017-05-30T20:07:24Z,Business Finance,232845,2017-05-30,20:07:24Z,2017,5,30
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2 hours,2016-12-13T14:57:18Z,Business Finance,255200,2016-12-13,14:57:18Z,2016,12,13

# Exploratory Data Analysis

In [63]:
df_org.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3683 entries, 0 to 3682
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   course_id            3683 non-null   int64
 1   course_title         3683 non-null   object
 2   url                  3683 non-null   object
 3   is_paid              3683 non-null   bool
 4   price                3683 non-null   int64
 5   num_subscribers      3683 non-null   int64
 6   num_reviews          3683 non-null   int64
 7   num_lectures         3683 non-null   int64
 8   level                3683 non-null   object
 9   content_duration     3683 non-null   object
 10  published_timestamp  3683 non-null   object
 11  subject              3683 non-null   object
 12  profit               3683 non-null   int64
 13  published_date       3683 non-null   object
 14  published_time       3682 non-null   object
 15  year                 3683 non-null   int64
 16  month                3683 non-null   int64
 17  day                  3683 non-null   int64
dtypes: bool(1), int64(9), object(8)
memory usage: 492.9+ KB

In [64]:
df_org.isnull().sum()

course_id              0
course_title           0
url                    0
is_paid                0
price                  0
num_subscribers        0
num_reviews            0
num_lectures           0
level                  0
content_duration       0
published_timestamp    0
subject                0
profit                 0
published_date         0
published_time         1
year                   0
month                  0
day                    0
dtype: int64

In [6]:
#data set have no misssing values

# Creating the copy of the dataset

We create a copy of the data set so that we can use columns useful for recommending the similar courses and and dropping the columns that are not very useful for recommending courses. we keep the original dataset because while recommending the courses we need to print all the columns as our output so that user can see all the information related to recommended courses.

In [65]:
df=df_org.copy()

In [66]:
df

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,profit,published_date,published_time,year,month,day
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5 hours,2017-01-18T20:58:58Z,Business Finance,429400,2017-01-18,20:58:58Z,2017,1,18
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39 hours,2017-03-09T16:34:20Z,Business Finance,209400,2017-03-09,16:34:20Z,2017,3,9
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5 hours,2016-12-19T19:26:30Z,Business Finance,97830,2016-12-19,19:26:30Z,2016,12,19
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3 hours,2017-05-30T20:07:24Z,Business Finance,232845,2017-05-30,20:07:24Z,2017,5,30
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2 hours,2016-12-13T14:57:18Z,Business Finance,255200,2016-12-13,14:57:18Z,2016,12,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3678,775618,Learn jQuery from Scratch - Master of JavaScri...,https://www.udemy.com/easy-jquery-for-beginner...,True,100,1040,14,21,All Levels,2 hours,2016-06-14T17:36:46Z,Web Development,104000,2016-06-14,17:36:46Z,2016,6,14
3679,1088178,How To Design A WordPress Website With No Codi...,https://www.udemy.com/how-to-make-a-wordpress-...,True,25,306,3,42,Beginner Level,3.5 hours,2017-03-10T22:24:30Z,Web Development,7650,2017-03-10,22:24:30Z,2017,3,10
3680,635248,Learn and Build using Polymer,https://www.udemy.com/learn-and-build-using-po...,True,40,513,169,48,All Levels,3.5 hours,2015-12-30T16:41:42Z,Web Development,20520,2015-12-30,16:41:42Z,2015,12,30
3681,905096,CSS Animations: Create Amazing Effects on Your...,https://www.udemy.com/css-animations-create-am...,True,50,300,31,38,All Levels,3 hours,2016-08-11T19:06:15Z,Web Development,15000,2016-08-11,19:06:15Z,2016,8,11
3682,297602,Using MODX CMS to Build Websites: A Beginner's...,https://www.udemy.com/using-modx-cms-to-build-...,True,45,901,36,20,Beginner Level,2 hours,2014-09-28T19:51:11Z,Web Development,40545,2014-09-28,19:51:11Z,2014,9,28

# Dropping columns that are not necessary for NLP model training

In [67]:
df.drop(['url','is_paid','price','num_subscribers','num_reviews','num_lectures','course_id','published_timestamp','profit','published_date','published_time','year','month','day'], axis=1,inplace=True)

In [68]:
df.head()

,course_title,level,content_duration,subject
0,Ultimate Investment Banking Course,All Levels,1.5 hours,Business Finance
1,Complete GST Course & Certification - Grow You...,All Levels,39 hours,Business Finance
2,Financial Modeling for Business Analysts and C...,Intermediate Level,2.5 hours,Business Finance
3,Beginner to Pro - Financial Analysis in Excel ...,All Levels,3 hours,Business Finance
4,How To Maximize Your Profits Trading Options,Intermediate Level,2 hours,Business Finance

# Declaring TF-IDF and removing stop words

In [108]:
from sklearn.feature_extraction.text import TfidfVectorizer


tfv = TfidfVectorizer(min_df=3,  max_features=None, 
            strip_accents='unicode', analyzer='word',token_pattern=r'\w{1,}',
            ngram_range=(1, 3),
            stop_words = 'english')

# Filling NaNs with empty string
df['cleaned'] = df['subject'].fillna('')

In [109]:
df.head()

,course_title,level,content_duration,subject,cleaned
0,Ultimate Investment Banking Course,All Levels,1.5 hours,Business Finance,Business Finance
1,Complete GST Course & Certification - Grow You...,All Levels,39 hours,Business Finance,Business Finance
2,Financial Modeling for Business Analysts and C...,Intermediate Level,2.5 hours,Business Finance,Business Finance
3,Beginner to Pro - Financial Analysis in Excel ...,All Levels,3 hours,Business Finance,Business Finance
4,How To Maximize Your Profits Trading Options,Intermediate Level,2 hours,Business Finance,Business Finance

# Making sparse matrix of the dataset

In [110]:
# Fitting the TF-IDF on the 'cleaned' text
tfv_matrix = tfv.fit_transform(df['cleaned'])

In [111]:
tfv_matrix

<3683x12 sparse matrix of type '<class 'numpy.float64'>'
	with 11049 stored elements in Compressed Sparse Row format>

In [112]:
tfv_matrix.shape

(3683, 12)

In [113]:
tm=tfv_matrix

In [114]:
import scipy.sparse

In [115]:
tfidfcheck=pd.DataFrame.sparse.from_spmatrix(tm)

In [116]:
tfidfcheck

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.57735,0.57735,0.0,0.00000,0.57735,0.0,0.0,0.0,0.0,0.0,0.00000,0.00000
1,0.57735,0.57735,0.0,0.00000,0.57735,0.0,0.0,0.0,0.0,0.0,0.00000,0.00000
2,0.57735,0.57735,0.0,0.00000,0.57735,0.0,0.0,0.0,0.0,0.0,0.00000,0.00000
3,0.57735,0.57735,0.0,0.00000,0.57735,0.0,0.0,0.0,0.0,0.0,0.00000,0.00000
4,0.57735,0.57735,0.0,0.00000,0.57735,0.0,0.0,0.0,0.0,0.0,0.00000,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...
3678,0.00000,0.00000,0.0,0.57735,0.00000,0.0,0.0,0.0,0.0,0.0,0.57735,0.57735
3679,0.00000,0.00000,0.0,0.57735,0.00000,0.0,0.0,0.0,0.0,0.0,0.57735,0.57735
3680,0.00000,0.00000,0.0,0.57735,0.00000,0.0,0.0,0.0,0.0,0.0,0.57735,0.57735
3681,0.00000,0.00000,0.0,0.57735,0.00000,0.0,0.0,0.0,0.0,0.0,0.57735,0.57735
3682,0.00000,0.00000,0.0,0.57735,0.00000,0.0,0.0,0.0,0.0,0.0,0.57735,0.57735

# making sigmoid kernel

We make a sigmoid kernel which stores the similarity score between each each row of cleaned column with every other rows these similarity scores will tell us how much the given row is related to other rows in the dataset and by this we can find similar courses for recommendations. The values of sigmoid kernel is between 0 and 1 since it uses sigmoid function.

In [117]:
from sklearn.metrics.pairwise import sigmoid_kernel

# Compute the sigmoid kernel
sig = sigmoid_kernel(tfv_matrix, tfv_matrix)

In [118]:
sig.shape

(3683, 3683)

In [119]:
sig

array([[0.79443195, 0.79443195, 0.79443195, ..., 0.76159416, 0.76159416,
        0.76159416],
       [0.79443195, 0.79443195, 0.79443195, ..., 0.76159416, 0.76159416,
        0.76159416],
       [0.79443195, 0.79443195, 0.79443195, ..., 0.76159416, 0.76159416,
        0.76159416],
       ...,
       [0.76159416, 0.76159416, 0.76159416, ..., 0.79443195, 0.79443195,
        0.79443195],
       [0.76159416, 0.76159416, 0.76159416, ..., 0.79443195, 0.79443195,
        0.79443195],
       [0.76159416, 0.76159416, 0.76159416, ..., 0.79443195, 0.79443195,
        0.79443195]])

In [120]:
sig[0]

array([0.79443195, 0.79443195, 0.79443195, ..., 0.76159416, 0.76159416,
       0.76159416])

In [121]:
# Reverse mapping of indices and titles
indices = pd.Series(df.index, index=df['course_title']).drop_duplicates()

In [122]:
indices

course_title
Ultimate Investment Banking Course                                0
Complete GST Course & Certification - Grow Your CA Practice       1
Financial Modeling for Business Analysts and Consultants          2
Beginner to Pro - Financial Analysis in Excel 2017                3
How To Maximize Your Profits Trading Options                      4
                                                               ...
Learn jQuery from Scratch - Master of JavaScript library       3678
How To Design A WordPress Website With No Coding At All        3679
Learn and Build using Polymer                                  3680
CSS Animations: Create Amazing Effects on Your Website         3681
Using MODX CMS to Build Websites: A Beginner's Guide           3682
Length: 3683, dtype: int64

In [123]:
indices['Ultimate Investment Banking Course']

0

In [124]:
sig[0]

array([0.79443195, 0.79443195, 0.79443195, ..., 0.76159416, 0.76159416,
       0.76159416])

In [125]:
list(enumerate(sig[indices['Ultimate Investment Banking Course']]))[0:25]
#seeing 25 elements of the list

[(0, 0.7944319501654964),
 (1, 0.7944319501654964),
 (2, 0.7944319501654964),
 (3, 0.7944319501654964),
 (4, 0.7944319501654964),
 (5, 0.7944319501654964),
 (6, 0.7944319501654964),
 (7, 0.7944319501654964),
 (8, 0.7944319501654964),
 (9, 0.7944319501654964),
 (10, 0.7944319501654964),
 (11, 0.7944319501654964),
 (12, 0.7944319501654964),
 (13, 0.7944319501654964),
 (14, 0.7944319501654964),
 (15, 0.7944319501654964),
 (16, 0.7944319501654964),
 (17, 0.7944319501654964),
 (18, 0.7944319501654964),
 (19, 0.7944319501654964),
 (20, 0.7944319501654964),
 (21, 0.7944319501654964),
 (22, 0.7944319501654964),
 (23, 0.7944319501654964),
 (24, 0.7944319501654964)]

In [126]:
sorted(list(enumerate(sig[indices['Ultimate Investment Banking Course']])), key=lambda x: x[1], reverse=True)[0:25]
#seeing 25 elements of the list

[(0, 0.7944319501654964),
 (1, 0.7944319501654964),
 (2, 0.7944319501654964),
 (3, 0.7944319501654964),
 (4, 0.7944319501654964),
 (5, 0.7944319501654964),
 (6, 0.7944319501654964),
 (7, 0.7944319501654964),
 (8, 0.7944319501654964),
 (9, 0.7944319501654964),
 (10, 0.7944319501654964),
 (11, 0.7944319501654964),
 (12, 0.7944319501654964),
 (13, 0.7944319501654964),
 (14, 0.7944319501654964),
 (15, 0.7944319501654964),
 (16, 0.7944319501654964),
 (17, 0.7944319501654964),
 (18, 0.7944319501654964),
 (19, 0.7944319501654964),
 (20, 0.7944319501654964),
 (21, 0.7944319501654964),
 (22, 0.7944319501654964),
 (23, 0.7944319501654964),
 (24, 0.7944319501654964)]

# Defining function that returns the recommendations

In [127]:
def give_rec(title, sig=sig):
    # Get the index corresponding to given course
    idx = indices[title]

    # Get the pairwsie similarity scores with given course with every available course in the data set
    sig_scores = list(enumerate(sig[idx]))

    # Sort the recommended courses
    sig_scores = sorted(sig_scores, key=lambda x: x[1], reverse=True)

    # Scores of the 10 most similar courses
    sig_scores = sig_scores[1:11]

    # get courses indices for top 10 recommended courses
    course_indices = [i[0] for i in sig_scores]

    # Top 10 most similar courses
    return df_org.iloc[course_indices]

# finding a course using keywords

we find list of similar courses using keywords so that user can find similar courses even without knowing name of the courses available in the data set. we use get_close_matches function to get the closest match of the keyword from difflib library then we take the most closest match and then recommend courses using that course.

In [128]:
import difflib

In [129]:
namelist=df['course_title'].tolist()

In [130]:
namelist[0:100]
#seeing 25 elements of the list

['Ultimate Investment Banking Course',
 'Complete GST Course & Certification - Grow Your CA Practice',
 'Financial Modeling for Business Analysts and Consultants',
 'Beginner to Pro - Financial Analysis in Excel 2017',
 'How To Maximize Your Profits Trading Options',
 'Trading Penny Stocks: A Guide for All Levels In 2017',
 'Investing And Trading For Beginners: Mastering Price Charts',
 'Trading Stock Chart Patterns For Immediate, Explosive Gains',
 'Options Trading 3 : Advanced Stock Profit and Success Method',
 'The Only Investment Strategy You Need For Your Retirement',
 "Forex Trading Secrets of the Pros With Amazon's AWS",
 'Trading Options With Money Flow',
 'Financial Management Risk and Return For Securities',
 'Forex Trading Course: Work Smarter Not Harder Proven Results',
 'Python Algo Trading: Sentiment Trading with News',
 'Short Selling: Learn To Sell Stocks Before The Fall',
 'Basic Technical Analysis: Learn the structure of the market',
 'The Complete Chart Pattern Trading Course: A Proven Approach',
 '7 Deadly Mistakes of Investing that Will Slash Your Profits!',
 'Financial Statements Made Easy',
 'Winning Forex Trading with Live Forex Trading Examples',
 'Forex Traders - Create Your First Trading Robot. No Coding!',
 'Create A Business From Home Trading Stocks Today In 2017',
 'Introduction to Accounting : Mastering Financial Statements',
 'The Complete Ethereum Course: Get .01 Ether In Your Wallet',
 'Beginner to Pro in PowerPoint: Complete PowerPoint Training',
 'Investing 101: The Complete Online Investing Course',
 'Create Your Own Hedge Fund: Trade Stocks Like A Fund Manager',
 'Learn MQL5: Build an 8-Currency Hedging Robot (MetaTrader 5)',
 'Forex Trading: Your Complete Guide to Get Started Like a Pro',
 'Python Algo Stock Trading: Automate Your Trading!',
 'THE Forex Robot: Incredible ROI (Robot Included)',
 'The Complete Bitcoin Course: Get .001 Bitcoin In Your Wallet',
 'Mastering High Probability Iron Condor Options Trading',
 'The Complete Short Course on Ethereum',
 'Options Trading Stocks: Proven Toolbox For Financial Success',
 'Forex Trading A-Z™ - With LIVE Examples of Forex Trading',
 'Introduction to Finance, Accounting, Modeling and Valuation',
 'Beginner to Pro in Excel: Financial Modeling and Valuation',
 'The Complete Investment Banking Course 2017',
 'The Complete Financial Analyst Course 2017',
 'Python for Finance: Investment Fundamentals & Data Analytics',
 'Financial Modeling for Startups & Small Businesses',
 'Options Trading - How to Win with Weekly Options',
 'Black Algo Trading: Build Your Trading Robot',
 'Accounting & Financial Statement Analysis: Complete Training',
 'Cryptocurrency Trading: Complete Guide To Trading Altcoins',
 'Forex Robots: Expect To Earn 175% P.A. Forex Robot Included!',
 'Three Steps Trading - Live Trading - Real Account',
 'Option Trading for Rookies:  Understand Options Completely',
 'How I Learned Stock Trading (and How You Can Too)',
 'Learn to Trade for Profit: Find and Trade Winning Stocks',
 'Trading Inside Bars - Master 1 Easy Pattern To Be Successful',
 'Four Fundamentals of Financial Planning',
 'Options Trading - Calendar Spread Course for Every Trader',
 'Dividend Investing: Build Your Portfolio for a Better Future',
 'Learn Accounting. Understand Business.',
 'How to Consistently Win Trading Stocks in 30 Days or Less',
 "A Beginner's Guide to Quantopian Futures API",
 'How to Buy Cheap Options - Options Trading Pricing Model',
 'Excel Crash Course: Master Excel for Financial Analysis',
 'Comprehensive Guide to Financial Markets, Investing &Trading',
 'Stock Trading Ninja: Complete System For Trading Success',
 'Hedge and Mutual Fund Careers: The Complete Guide',
 'Algorithmic Trading In Forex: Create Your First Forex Robot!',
 'The Power Modeling Bootcamp: Advanced Excel in 10 Days',
 'Options Trading Basics (3-Course Bundle)',
 'How to Win 97% of Your Options Trades',
 'How I Make Consistent Returns Trading Options',
 'Forex Strategies: Kelly Criterion, Larry Williams and more!',
 'Elite Trend Trader: Learn To Trade Stocks, Options & Forex',
 'Options Trading Introduction: Day Trade Stock Options',
 'The Almost Perfect Options Trading Strategy System - Unique',
 'Forex Trading -  Learn to Trade Forex Like the Banks',
 'Learn to Trade for Profit:Trading with Japanese Candlesticks',
 'The Most Powerful Options Spread Trading Front Ratio Spread',
 'What Finance Job is for You? Explanation of 14 Finance Roles',
 'The Blueprint for Successful Stock Trading',
 'Trading for Beginners - Intermediate Level',
 'Start Trading Stocks Using Technical Analysis!',
 'Learn How to Set Up an Incubator Hedge Fund - Step-by-Step',
 'VPS for Forex Trading - Protect Your Forex Robots',
 'Introduction to Accounting: The Language of Business',
 'Basic Excel for Basic Bookkeeping and Accounting',
 'Using \'The Greeks To Understand Options"',
 'Trading Options For Consistent Returns: Calendar Spreads',
 'How to Create Your Personal Budget',
 'The Complete Value Investing Course: A Proven Approach',
 'FOREX Trading with Price Action',
 'Emini ES Futures - Advanced Non Directional Options Trading',
 'Forex Trading - Advanced Fundamental Analysis',
 'How To Invest With Tiny Capital In Stocks ?',
 'Learn How To Successfully Trade Stocks: In 5 Simple Steps',
 'Test your knowledge in Basics of Accounting',
 'Forex MetaTrader 4: Master MT4 Like A Pro Forex Trader',
 'Test your Knowledge in Cost Accounting',
 'Intermediate Options trading concepts for Stocks and Options',
 'Options Trading 101: The Basics',
 'Practical Accounts APP Overview',
 'Bitcoin Profits for Beginners']

In [132]:
word="Bitcoin Profits for Beginners"

In [133]:
simlist=difflib.get_close_matches(word, namelist)
simlist

['Bitcoin Profits for Beginners',
 'Bitcoin For Beginners',
 'Sketchbook Pro for Beginners']

# Handling errors and no output senarioes

In [134]:
try: 
        findf=give_rec(simlist[0])
        findf=findf.reset_index(drop=True)
except:
        findf = pd.DataFrame()

In [97]:
findf

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,profit,published_date,published_time,year,month,day
0,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39 hours,2017-03-09T16:34:20Z,Business Finance,209400,2017-03-09,16:34:20Z,2017,3,9
1,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5 hours,2016-12-19T19:26:30Z,Business Finance,97830,2016-12-19,19:26:30Z,2016,12,19
2,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3 hours,2017-05-30T20:07:24Z,Business Finance,232845,2017-05-30,20:07:24Z,2017,5,30
3,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2 hours,2016-12-13T14:57:18Z,Business Finance,255200,2016-12-13,14:57:18Z,2016,12,13
4,192870,Trading Penny Stocks: A Guide for All Levels I...,https://www.udemy.com/trading-penny-stocks-a-g...,True,150,9221,138,25,All Levels,3 hours,2014-05-02T15:13:30Z,Business Finance,1383150,2014-05-02,15:13:30Z,2014,5,2
5,739964,Investing And Trading For Beginners: Mastering...,https://www.udemy.com/investing-and-trading-fo...,True,65,1540,178,26,Beginner Level,1 hour,2016-02-21T18:23:12Z,Business Finance,100100,2016-02-21,18:23:12Z,2016,2,21
6,403100,"Trading Stock Chart Patterns For Immediate, Ex...",https://www.udemy.com/trading-chart-patterns-f...,True,95,2917,148,23,All Levels,2.5 hours,2015-01-30T22:13:03Z,Business Finance,277115,2015-01-30,22:13:03Z,2015,1,30
7,476268,Options Trading 3 : Advanced Stock Profit and ...,https://www.udemy.com/day-trading-stock-option...,True,195,5172,34,38,Expert Level,2.5 hours,2015-05-28T00:14:03Z,Business Finance,1008540,2015-05-28,00:14:03Z,2015,5,28
8,1167710,The Only Investment Strategy You Need For Your...,https://www.udemy.com/the-only-investment-stra...,True,200,827,14,15,All Levels,1 hour,2017-04-18T18:13:32Z,Business Finance,165400,2017-04-18,18:13:32Z,2017,4,18
9,592338,Forex Trading Secrets of the Pros With Amazon'...,https://www.udemy.com/trading-with-amazons-aws...,True,200,4284,93,76,All Levels,5 hours,2015-09-11T16:47:02Z,Business Finance,856800,2015-09-11,16:47:02Z,2015,9,11

In [135]:
if findf.empty:
        ms='Sorry! we did not find any matching courses, Try adding more keywords in your search.'
        ht=' '
else:
        ht='done'
        ms='Here are some recommendations :'

In [136]:
ms

'Here are some recommendations :'

In [137]:
ht

'done'